name: freej
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+6

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #firebase
  firebase_core: ^1.15.0
  cloud_firestore: ^3.1.13
  firebase_storage: ^10.2.13

  #UI
  cupertino_icons: ^1.0.2
  responsive_framework: ^0.1.5
  cached_network_image: ^3.2.0
  webview_flutter: ^3.0.1
  lottie: ^1.2.2

  #Essentials
  provider: ^6.0.2

  #Services
  intl: ^0.17.0
  jwt_decode: ^0.3.1
  shared_preferences: ^2.0.13
  # package_info_plus: ^1.4.0
  url_launcher: ^6.0.20
  image_picker: ^0.8.5
  share_plus: ^4.0.4
  timeago: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/languages/

  fonts:
    - family: FzIcons
      fonts:
        - asset: assets/fonts/FzIcons.ttf

    - family: Phosphor
      fonts:
        - asset: assets/fonts/phosphor_icons.ttf

    - family: FredokaOne
      fonts:
        - asset: assets/fonts/FredokaOne-Regular.ttf

    - family: VarelaRound
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf

    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal/Tajawal-Black.ttf
          weight: 900
